[SDE-1888] Adding RBAC rules for Addon ODF
openshift/managed-cluster-config pull request #1149
Opened 2022-04-28 13:19 UTC by apahim

Signed-off-by: Amador Pahim <apahim@redhat.com>

### What type of PR is this?
_(bug/feature/cleanup/documentation)_

### What this PR does / why we need it?

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

2022-05-05 17:05 UTC, jewzaam requested changes
Labels do not match backplane name and make it hard to understand how everything is related.  Use "addon-odf" in everything, not "addon-ocs".  Note it could be "addon-odf-ocs...", but the key is "addon-odf" consistency.

Namespace referenced in SubjectPermissions doesn't exist, probably should be "openshift-backplane-addon-odf"?

2022-05-05 18:59 UTC, apahim commented on deploy/backplane/addon-odf/config.yaml
> +    api.openshift.com/addon-ocs-provider: "true"
ODF is the team, OCS-Consumer and OCS-Provider are the Addons. I will clean this up ;)

2022-05-05 19:41 UTC, apahim commented on deploy/backplane/addon-odf/ocs-consumer/10-mtsre-ocs-consumer-admins.SubjectPermission.yml
> +  subjectName: system:serviceaccounts:openshift-backplane-odf-dev
fixed

2022-05-05 19:56 UTC, jewzaam approved these changes
Generally looks good.  I can approve.  I am curious why backplane-mtsre-ocs-consumer-cr-admins and backplane-mtsre-ocs-provider-cr-admins ClusterRoles are not reused for openshift-backplane-odf SA's.  Is there a reason to duplicate?  Given MTSRE-529 states this is for initial support it implies to me the same permissions mtsre has will be needed by odf.

/approve

2022-05-05 20:14 UTC, apahim commented
Good point... I was just thinking about separation, but it makes sense to dedup there, specially when the ClusterRoles can change while things settle. Updating.

2022-05-05 20:32 UTC, apahim commented
updated!

2022-05-05 22:11 UTC, jewzaam approved these changes

2022-05-05 22:42 UTC, cblecker commented
/hold

2022-05-10 12:24 UTC, apahim commented
Can we please either merge this or decide how we are going to give ODF Dev Team access instead?

2022-05-10 20:59 UTC, cblecker requested changes

2022-05-10 20:59 UTC, cblecker commented on deploy/backplane/odf/10-odf-readers-cluster.ClusterRole.yml
> +            - "true"
Does the ODF team need read access to every namespace?

2022-05-13 18:17 UTC, apahim commented
Ping. Anything missing here?

2022-05-13 19:43 UTC, cblecker commented
/lgtm
/approve
/hold cancel

2022-05-13 19:51 UTC, merged