Allow dedicated-admins to manage UWM Alertmanager
openshift/managed-cluster-config pull request #1290
Opened 2022-10-03 17:36 UTC by fahlmant

### What type of PR is this?
_(bug/feature/cleanup/documentation)_

Feature

### What this PR does / why we need it?

Implements the needed changes to enable dedicated-admins to manage UWM Alertmanager configuration

### Which Jira/Github issue(s) this PR fixes?
SDE-1112

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ x] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2022-10-03 17:58 UTC, jewzaam requested changes

2022-10-03 17:58 UTC, jewzaam commented on deploy/osd-user-workload-monitoring/04-dedicated-admins-uwm-am-secret-role.Role.yaml
> +  - '*'
Do we want to permit delete?  CMO manages (creates) the secret.  I don't know if on delete CMO will recreate it.  And form what I recall of how the create verb functions you won't actually be able to create the resource when using `resourceNames`.  So I think verbs should be: get, list, watch, update, patch.

2022-10-03 18:38 UTC, jewzaam approved these changes

2022-10-03 18:38 UTC, jewzaam commented
/lgtm

2022-10-03 18:45 UTC, merged

2022-10-05 11:17 UTC, fahlmant commented
OSD link https://issues.redhat.com/browse/OSD-13412