Add delete/patch permissions to cpms for SREs
openshift/managed-cluster-config pull request #1411
Opened 2023-01-10 21:02 UTC by AlexVulaj

As part of OCP 4.12, ControlPlaneMachineSet (CPMS) was added as a new custom resource in openshift-machine-api. SREs need these added permissions to properly service this CR in new clusters.

2023-01-10 21:30 UTC, jewzaam requested changes

2023-01-10 21:30 UTC, jewzaam commented on deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
> +- apiGroups:
```suggestion
# SRE can delete and patch ControlPlaneMachineSet https://issues.redhat.com/browse/OSD-14581 
- apiGroups:
```

2023-01-10 21:30 UTC, jewzaam commented on deploy/backplane/srep/10-srep-admins-cluster.ClusterRole.yml
> +  - controlplanemachineset
```suggestion
  - controlplanemachinesets
```

2023-01-10 21:35 UTC, jewzaam commented
/hold
/lgtm

2023-01-10 22:06 UTC, AlexVulaj commented
Generated files are missing from this PR (and likely causing the build failure) because I'm having issues running `make` on my m1 mac with podman. If anyone wants to pull this down and generate those it would be greatly appreciated, in the meantime I'll keep investigating.

2023-01-10 22:15 UTC, mrbarge commented
@AlexVulaj in case it helps, I raised a PR to your branch with the generated files as I couldn't commit directly to your own.
https://github.com/AlexVulaj/managed-cluster-config/pull/1

2023-01-11 16:24 UTC, AlexVulaj commented
@cblecker This is an action that will always be the exact same every time, and I don't think it'll necessarily be a regular thing SREs need to do daily.  I'm pinging @iamkirkbater for a second opinion here.

2023-01-11 16:34 UTC, fahlmant commented
@AlexVulaj Is there an associated Jira? 

Would patch be sufficient? IIUC, a delete will cause rolling reboots of the control plane nodes, is that necessary for common actions SREP should take? If not, it might be better to gate that one behind elevation because it could be more sensitive.

2023-01-11 18:39 UTC, AlexVulaj commented
@fahlmant Based on our conversations in slack, it looks like our path forward here is to go through with what's shown.  I've also added the JIRA ticket to this PR's description.

2023-01-11 18:49 UTC, fahlmant commented
@AlexVulaj thanks for the update. I don't see any description of what causes the rolling reboots though. Is that done through a PATCH?

2023-01-11 19:03 UTC, AlexVulaj commented
@fahlmant In this situation, there won't be any rolling reboots. When CPMS comes back up, it will already have its spec updated to match the current state of the machines, and thus will not perform any new actions on them.

In the case of CIO updates causing rolling reboots, this is happening because CIO is updating the machines while CPMS is Active, so CPMS triggers itself to bring those machines back into sync with what it believes to be the source of truth.

2023-01-11 19:05 UTC, fahlmant commented
I'm not asking about CIO specifically. I'm asking what sequence of events leads to a rolling reboot. If an SRE runs a patch on CPMS incorrectly, can they trigger a rolling reboot?

2023-01-11 19:14 UTC, AlexVulaj commented
@fahlmant Any update to the cpms spec will trigger a rolling reboot. If anything updates a machine behind the scenes, CPMS will replace just that machine. CPMS uses immutable infrastructure, so if it detects any drift then it will kill the out of date machine(s) and spin up new ones.

I'll note that CPMS allows a surge to 4 nodes as well, so it will make sure a new instance is ready to go with all workloads moved over before tearing down the old machine.

2023-01-11 19:16 UTC, fahlmant commented
Hmm so giving SREP patch is a bit dangerous without requiring elevation

2023-01-11 19:19 UTC, AlexVulaj commented
I don't necessarily disagree, my goal was to avoid generating compliance tickets every time an SRE needs to update a control plane. Maybe we do in fact want that, but I'll leave that decision up to you. We can always decline this PR and I can update my [SOP changes](https://github.com/openshift/ops-sop/pull/2371) to require `--as backplane-cluster-admin` for the delete/patch commands.

2023-01-11 19:48 UTC, AlexVulaj commented
Though there's still ongoing conversation about if we want to go through with this PR or not, I will note that I have in fact tested it on a staging cluster by pausing the hive syncset and manually adding these updated permissions to the `backplane-srep-admins-cluster` role. If we decide to move forward with this change, it's ready to go.

2023-01-11 21:34 UTC, jewzaam commented
With the risk of patch causing a rolling update I think relying on elevation will be better.  It's more paperwork and it will help ensure we don't do this accidentally.. nobody likes paperwork.  Long term we'll have the bug fixed and can have OCM manage this, SRE won't be manually resizing.  Assuming ADR (yet to be drafted) is accepted!

So I think we should ditch this PR and add elevation in the SOP @AlexVulaj

2023-01-12 13:42 UTC, AlexVulaj commented
@jewzaam sounds good!  I'll go forward with that.

2023-01-12 18:12 UTC, closed without merging