OSD-14190 : Review backplane permissions for Management and Service clusters
openshift/managed-cluster-config pull request #1449
Opened 2023-01-29 06:53 UTC by MitaliBhalla

### What type of PR is this?
Feature
_(bug/feature/cleanup/documentation)_

### What this PR does / why we need it?
Reviewing backplane permissions for Management and Service clusters 

### Which Jira/Github issue(s) this PR fixes?
OSD-14190
_Fixes #_

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2023-01-29 06:55 UTC, MitaliBhalla commented
Please note that this PR incoporates suggestions suggested by the review of https://github.com/openshift/managed-cluster-config/pull/1430 cc : @jewzaam

2023-01-29 08:16 UTC, MitaliBhalla commented
FYI : https://issues.redhat.com/browse/OSD-14582 , https://issues.redhat.com/browse/OSD-14190

2023-01-30 18:54 UTC, jewzaam requested changes
This PR does not include the 'backplane-dev' role.  And in review of utilization of this on hive shards I have concluded this is a permission that SRE does not need day to day.  I will create a card to remove this access.

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/management-cluster/10-backplane-dev.RoleBinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Remove this file.  I will put in a card and PR to remove this from hive with justification.

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/service-cluster/10-backplane-dev.RoleBinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Remove this file.  I will put in a card and PR to remove this from hive with justification.

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/management-cluster/10-srep-management-cluster-project.ClusteRole.yml
> +  - patch
SRE's ability to patch these resources is a concern to me.  They are managed from the SC via ManifestWorks.  Any changes made by SRE will be reconciled.  

```suggestion
```

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/service-cluster/10-srep-service-cluster-project.ClusteRole.yml
> +  - patch
Same concerns with management cluster in that we should be careful with patch.
Note that SC will not have these resources anyway as they're only managed on the MC.
But, recommend for consistency:
```suggestion
```

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/service-cluster/20-srep.SubjectPermission.yml
> +    namespacesAllowedRegex: "(^uhc-.*)"
```suggestion
    namespacesAllowedRegex: "(^uhc.*|^ocm.*)"
```

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/service-cluster/20-srep.SubjectPermission.yml
> +    namespacesAllowedRegex: "(^hypershift.*|^uhc-.*|^ocm-.*|^klusterlet.*|^open-cluster-management.*)"
```suggestion
    namespacesAllowedRegex: "(^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)"
```

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/management-cluster/20-srep.SubjectPermission.yml
> +    namespacesAllowedRegex: "(^uhc-.*)"
```suggestion
    namespacesAllowedRegex: "(^uhc.*|^ocm.*)"
```

2023-01-30 18:54 UTC, jewzaam commented on deploy/backplane/srep/hypershift/management-cluster/20-srep.SubjectPermission.yml
> +    namespacesAllowedRegex: "(^hypershift.*|^uhc-.*|^ocm-.*|^klusterlet.*|^open-cluster-management.*)"
```suggestion
    namespacesAllowedRegex: "(^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)"
```

2023-01-31 13:56 UTC, jewzaam approved these changes
/lgtm
/approve

2023-01-31 14:01 UTC, merged