Update control-plane-operator policy
openshift/managed-cluster-config pull request #1469
Opened 2023-02-08 02:59 UTC by csrwng

### What type of PR is this?
feature

### What this PR does / why we need it?
The control-plane-opertor needs additional permissions in order to create and destroy a default security group for NodePools where no security group is specified.

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_ HOSTEDCP-789

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2023-02-08 03:00 UTC, cblecker commented
/assign @jharrington22

2023-02-08 13:47 UTC, fahlmant commented
@csrwng Is this specific to hypershift?

2023-02-09 02:34 UTC, csrwng commented
@fahlmant yes it is. The entire control plane operator policy is only used in hypershift

2023-02-10 14:51 UTC, jewzaam requested changes
This is HS specific, should go in https://github.com/openshift/managed-cluster-config/blob/master/resources/sts/4.12/hypershift/ControlPlaneOperatorPolicy.json  ?

2023-02-10 15:14 UTC, jharrington22 commented
@csrwng as @jewzaam suggested could you also add these actions to the [policy](https://github.com/openshift/managed-cluster-config/blob/master/resources/sts/4.12/hypershift/ControlPlaneOperatorPolicy.json) in the HyperShift directory? The plan is to migrate from these to those newer policies which will contain IAM conditions to ensure we only operate on objects tagged by Red Hat.

2023-02-13 19:29 UTC, jharrington22 approved these changes
/lgtm

2023-02-13 19:47 UTC, merged