added lpsre to elevated perms
openshift/managed-cluster-config pull request #1492
Opened 2023-02-14 07:12 UTC by vinaybommana

### What type of PR is this?
cleanup for the elevated perms for lpsre user

### What this PR does / why we need it?
lpsre needs elevated sre backplane cluster admin perms

### Which Jira/Github issue(s) this PR fixes?
https://issues.redhat.com/browse/MTSRE-965

2023-02-14 10:29 UTC, Nanyte25 commented
@jharrington22 or @rafael-azevedo can we get this reviewed and or approved thanks

2023-02-14 10:29 UTC, Nanyte25 commented
/assign dustman9000

2023-02-14 20:28 UTC, jewzaam commented
/hold

2023-02-14 20:29 UTC, jewzaam requested changes
JIRA card has no justification for the requested access nor sign off for that access.  Let's take this to JIRA before committing to changes in MCC.

2023-02-14 22:12 UTC, brizrobbo commented
@jewzaam & @dustman9000 The JIRA is here: https://issues.redhat.com/browse/MTSRE-965

2023-02-14 22:26 UTC, dustman9000 commented
@vinaybommana - Can you just update the `lpsre` RBAC to allow for restarting deployments? We will not allow elevating to cluster-admin in the long term. 
RBAC needed for what's in the Jira:
```
rules:
 - apiGroups: ["apps", "extensions"]
   resources: ["deployments"]
   resourceNames: ["rhmi-operator"]
   verbs: ["get", "patch"]
```

2023-03-06 13:07 UTC, vinaybommana commented
/re-open

2023-03-06 13:16 UTC, vinaybommana commented
@dustman9000 wrt to https://issues.redhat.com/browse/OSD-15463 can you please take a look at this PR
cc @apahim

2023-03-06 18:37 UTC, cblecker commented
This isn't required. Let's take discussion to JIRA.
/close

2023-03-06 18:37 UTC, closed without merging