Adding a config.yaml for every SSS
openshift/managed-cluster-config pull request #1591
Opened 2023-04-07 08:51 UTC by bdematte

### What type of PR is this?
Feature preparation

### What this PR does / why we need it?
As a preparation for OSD-15267 (to make it easier to review), adding explicit default config.yaml where it is currently implicit (with the objective of making it mandatory in OSD-15267).

### Which Jira/Github issue(s) this PR fixes?

OSD-15553

### Special notes for your reviewer:
Templates aren't modified by the MR which is validating it is doing its expected duty. 

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2023-04-07 12:34 UTC, jewzaam requested changes
Add enforcement in PR check, when `./hack/app_sre_pr_check.sh` is run if a `config.yaml` is missing that should exist it will fail with a user friendly message.

Alternative (which I don't particularlly like) is have `make` generate the "default" config.yaml.  Would want it to be a new make target and be added to the list of default targets.

2023-04-07 14:07 UTC, bdematte commented
@jewzaam the idea was to enforce it within [OSD-15267](https://issues.redhat.com//browse/OSD-15267) in order to bundle the changes of expectations/process in 1 step for contributors and make it clearer (with proper mail communication to be sent upon merge of MR for OSD-15267 )

2023-04-07 16:06 UTC, jewzaam commented
@bdematte since this is adding the config in every dir where it is needed you're better off putting in the enforcement here.  I guess alternative is to add that plus any drift (new config.yaml needed) later, but I don't see why not just do it now.

2023-04-11 12:06 UTC, jewzaam approved these changes

2023-04-11 12:08 UTC, jewzaam commented
Failure when config is missing works great for SSS generation.
Verified it fails with a useful message for pr check as well.
And with all the changes, this is a noop for the hive templates.

/approve
/lgtm

2023-04-11 12:14 UTC, merged