Add read perms for CEE on SC/MC
openshift/managed-cluster-config pull request #1667
Opened 2023-05-08 05:19 UTC by wanghaoran1988

### What type of PR is this?
_(bug/feature/cleanup/documentation)_
Feature
### What this PR does / why we need it?
This add read permission on MC/SC for CEE
### Which Jira/Github issue(s) this PR fixes?

_Fixes #_ https://issues.redhat.com/browse/OSD-15997

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [x] Included documentation changes with PR
- [x] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2023-05-09 17:47 UTC, cblecker commented
/hold
This shouldn't be necessary, as CEE should already have this access on SCs/MCs (OSDFM has tested this). Have we tested this access?

2023-05-10 03:52 UTC, wanghaoran1988 commented
> 

@cblecker I can confirm CEE does not have those perms I am trying to add. I copied those from https://github.com/openshift/managed-cluster-config/tree/master/deploy/backplane/srep/hypershift

2023-05-12 03:41 UTC, mjlshen commented on deploy/backplane/cee/hypershift/management-cluster/10-cee-management-cluster-cluster.ClusteRole.yml
nit: a couple of these files are named `ClusteRole` instead of `ClusterRole` and reference SRE instead of MCS

2023-05-15 01:30 UTC, wanghaoran1988 commented on deploy/backplane/cee/hypershift/management-cluster/10-cee-management-cluster-cluster.ClusteRole.yml
good catch, updated now.

2023-05-15 13:51 UTC, jewzaam requested changes
I wouldn't expect permissions on SC and MC to be the same.  The CAPI resources requested (cluster.x-k8s.io) in SC are not used, it's OSD so it's MAPI right now.  CAPI comes in only in the context of HCP node pools, so on the MC.  Also inconsistent in how cluster and project scoped resources are enumerated.  Why list out everything for project and use '*' for cluster?  Is there some resource you do not want to include in the project scope?

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/management-cluster/10-cee-management-cluster-cluster.ClusterRole.yml
> +# SRE can view ACM Policy at cluster scope
```suggestion
# CEE can view ACM Policy at cluster scope
```

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/management-cluster/10-cee-management-cluster-cluster.ClusterRole.yml
> +# SRE can view networking resources at cluster scope
```suggestion
# CEE can view networking resources at cluster scope
```

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/management-cluster/10-cee-management-cluster-cluster.ClusterRole.yml
> +# SRE can view HCP resources at cluster scope
```suggestion
# CEE can view HCP resources at cluster scope
```

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/service-cluster/10-cee-service-cluster-cluster.ClusterRole.yml
> +# SRE can view ACM Policy at cluster scope
```suggestion
# CEE can view ACM Policy at cluster scope
```

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/service-cluster/10-cee-service-cluster-cluster.ClusterRole.yml
> +# SRE can view HCP resources at cluster scope
```suggestion
# CEE can view HCP resources at cluster scope
```

2023-05-15 13:51 UTC, jewzaam commented on deploy/backplane/cee/hypershift/service-cluster/10-cee-service-cluster-cluster.ClusterRole.yml
> +# SRE can view networking resources at cluster scope
```suggestion
# CEE can view networking resources at cluster scope
```

2023-05-16 04:10 UTC, wanghaoran1988 commented
> I wouldn't expect permissions on SC and MC to be the same. The CAPI resources requested (cluster.x-k8s.io) in SC are not used, it's OSD so it's MAPI right now. CAPI comes in only in the context of HCP node pools, so on the MC. Also inconsistent in how cluster and project scoped resources are enumerated. Why list out everything for project and use '*' for cluster? Is there some resource you do not want to include in the project scope?

Good point, I simply copied those perms from https://github.com/openshift/managed-cluster-config/tree/master/deploy/backplane/srep/hypershift , it looks like we need a change as well for srep hypershift perms. 
I removed the 'project' roles, since we do not need those project scoped perms.

2023-05-16 14:05 UTC, jewzaam approved these changes

2023-05-16 14:06 UTC, jewzaam commented
/lgtm
/hold cancel

2023-05-16 14:10 UTC, merged