mtsre-1450 initial commit of mcc to mitigate prom oom issue on odf
openshift/managed-cluster-config pull request #1822
Opened 2023-09-07 01:30 UTC by sclarkso

2023-09-07 03:22 UTC, supreeth7 commented
@sclarkso can you update the description? There's a good reason why we have PR templates in MCC, to give better context to reviewers.

2023-09-07 04:11 UTC, supreeth7 requested changes

2023-09-07 05:41 UTC, sclarkso commented on deploy/odf-prom-restart/01-mtsre-1450.Role.yaml
> +  resources:
The pod is always "prometheus-managed-ocs-prometheus-0" so I added that as the "resourceNames".

2023-09-12 05:58 UTC, wanghaoran1988 commented
/lgtm
/approve

2023-09-12 06:03 UTC, supreeth7 commented
/label tide/merge-method-squash

2023-09-12 06:11 UTC, merged