OSDOCS-7755 Adding documentation links to priority ROSA notifications
openshift/managed-cluster-config pull request #1860
Opened 2023-09-19 20:24 UTC by laubai

### What type of PR is this?
documentation

### What this PR does / why we need it?
MOBB-F2F: adding documentation URLs and/or more detail for DiskPressure and NetworkUnavailable notifications

### Which Jira/Github issue(s) this PR fixes?
Partial fix for
https://issues.redhat.com/browse/OSDOCS-7755
https://issues.redhat.com/browse/OSDOCS-7756

_Fixes #_

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2023-09-19 20:30 UTC, jewzaam commented
/hold

waiting for clarity on text review requirements

2023-09-20 13:03 UTC, arendej approved these changes
lgtm

2023-09-20 14:56 UTC, laubai commented
@jewzaam Added the MemoryPressure and PIDPressure information into the notifs.

2023-09-20 15:16 UTC, jewzaam requested changes

2023-09-20 15:16 UTC, jewzaam commented on deploy/ocm-agent-operator-managednotifications/node-condition/200-sre-node-condition-managed-notification.ManagedNotification.yaml
> +        PIDPressure condition is true for at least one worker. This means that more than the maximum allowed number of processes are present on a worker node. This is likely to create instability in
```suggestion
        PIDPressure condition is true for at least one worker. This means that more than the maximum allowed number of process identifiers are consumed on one or more worker nodes. This is likely to create instability in the node, as required system services may not be able to create new processes. Reduce the number of pods scheduled to the impacted nodes, or reduce the number of process identifiers consumed by applications on the impacted nodes.
```

No KCS on what PIDs are and how they're consumed?

2023-09-21 00:14 UTC, jewzaam commented
/hold cancel
/approve

2023-09-21 00:15 UTC, jewzaam approved these changes

2023-09-21 00:57 UTC, bchandra-ocp commented
/lgtm

2023-09-21 01:00 UTC, bchandra-ocp approved these changes
thanks

2023-09-21 01:05 UTC, merged

2023-09-21 13:51 UTC, arendej commented
/lgtm