Adding permissions in backplane for CEE to support ACS:CS
openshift/managed-cluster-config pull request #2153
Opened 2024-06-20 14:29 UTC by pat-cremin

### What type of PR is this?
Enabling access to ACS for CEE for GA

### What this PR does / why we need it?
Enabling access to ACS for CEE for GA
### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2024-06-20 15:00 UTC, Nanyte25 commented
/lgtm

2024-06-21 08:24 UTC, pat-cremin commented
/retest

2024-06-21 11:51 UTC, jewzaam commented
/hold

no jira link
no documentation updated

2024-06-21 13:47 UTC, pat-cremin commented
@jewzaam  I had Jira creation issues earlier. I have created and linked the Jira to the PR now.

2024-06-21 13:49 UTC, pat-cremin commented
re: `no documentation updated`

I see no documentation within the repo other than the general structure in the `deploy/backplane` README.md. Did I overlook something specific that you could point me to?

2024-06-21 14:49 UTC, jewzaam commented
> re: `no documentation updated`
> 
> I see no documentation within the repo other than the general structure in the `deploy/backplane` README.md. Did I overlook something specific that you could point me to?

https://github.com/openshift/managed-cluster-config/tree/master/docs/backplane

2024-06-21 17:01 UTC, jewzaam requested changes

2024-06-21 17:01 UTC, jewzaam commented on docs/backplane/requirements/cee/40-backplane-cee.md
> +resources under the mentioned namespaces.
```suggestion
## backplane-readers-cluster: `cluster`

Existing role, permission to view select resources at cluster scope.

## backplane-cee-readers-cluster: `cluster`

* view machine configurations
* view machines
* view api request counts
* view egress ips

## openshift-backplane-cee: `(^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*|^rhacs$|^rhacs-*)`

* view resources in namespaces using `dedicated-readers` role
```

2024-06-21 17:03 UTC, jewzaam commented
Suggested updates to the cee backplane requirements doc.  Will approve and ask someone lgtm and remove hold when doc updates are good enough.

/approve

2024-06-21 18:13 UTC, jewzaam approved these changes
/hold cancel

2024-06-21 18:16 UTC, robotmaxtron commented
/lgtm

2024-06-21 18:29 UTC, merged