CEE RBAC + Requirements
openshift/managed-cluster-config pull request #2165
Opened 2024-07-09 10:08 UTC by diakovnec

What type of PR is this?
(bug/feature/cleanup/documentation)

'make' doesn't get triggered https://github.com/openshift/managed-cluster-config/pull/2161 and https://github.com/openshift/managed-cluster-config/pull/2162

raising a new PR to see why actions failing to test with a freshly forked repo to see if it makes any diff 

was discussing this issue https://redhat-internal.slack.com/archives/C016S65RNG5/p1720078609433969

2024-07-09 10:09 UTC, diakovnec commented
with a new fork the action was created 

`[CEE RBAC + Requirements](https://github.com/diakovnec/managed-cluster-config/actions/runs/9855051983)
Make Generate #1: Commit [9c32ef6](https://github.com/diakovnec/managed-cluster-config/commit/9c32ef60b7c689608e328d26d6b88ee70ecf736e) pushed by [diakovnec](https://github.com/diakovnec)`

2024-08-12 12:49 UTC, jewzaam requested changes

2024-08-12 12:49 UTC, jewzaam commented on deploy/backplane/cee/01-cee-cluster-readers-cluster.ClusterRole.yml
> +  - '*'
```suggestion
  - clusterautoscalers
  - machineautoscalers
```

Been thinking about use of '*', probably best to be explicit generally so any additions in the future are not going to break the assumptions about non-sensitive data.

2024-08-12 12:49 UTC, jewzaam commented on docs/backplane/requirements/cee/20-machineautoscaler.md
> +- ROSA HCP
```suggestion
```

HCP does not expose autoscaling, this has to be managed / viewed via OCM or on management cluster hosting the control plane.

2024-08-13 13:31 UTC, jewzaam approved these changes
/lgtm

2024-08-13 13:31 UTC, jewzaam commented
/approve

2024-08-13 13:49 UTC, merged