Add tier2 role
openshift/managed-cluster-config pull request #2229
Opened 2024-09-25 17:54 UTC by iamkirkbater

### What type of PR is this?
Feature

### What this PR does / why we need it?
Adds MCS Tier Two support role to clusters so that they can use backplane to login. Direct Copy of the CEE role at this time. Milestone Two of the MCS Enablement Epic may give them additional permissions, but no extra permissions are given at this time.

### Which Jira/Github issue(s) this PR fixes?

_Fixes https://issues.redhat.com/browse/OSD-25352_

### Special notes for your reviewer:

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

2024-09-26 13:37 UTC, iamkirkbater commented
/approve cancel

I believe we need Architect review for permissions so I want to remove the approval so this doesn't accidentally get LGTM'd

2024-09-27 13:06 UTC, jewzaam requested changes
Not mentioned in docs:
* pcap-collector
* must-gather-operator
* CMO portforward

Are these necessary or an artifact of copy/paste?  Either remove or update docs please.

2024-09-27 13:06 UTC, jewzaam commented on deploy/backplane/mcs-tier-two/hypershift/service-cluster/10-mcs-tier-two-service-cluster-cluster.ClusterRole.yml
> +  - watch
```suggestion
```

Duplicate.

2024-09-27 13:06 UTC, jewzaam commented on deploy/backplane/mcs-tier-two/hypershift/service-cluster/20-mcs-tier-two.SubjectPermission.yml
> +  - view
```suggestion
  - backplane-readers-cluster
```

Inconsistent with docs.

2024-09-27 13:06 UTC, jewzaam commented on deploy/backplane/mcs-tier-two/hypershift/management-cluster/20-mcs-tier-two.SubjectPermission.yml
> +  - view
```suggestion
  - backplane-readers-cluster
```

Inconsistent with docs.

2024-09-27 18:02 UTC, jewzaam approved these changes
/approve

2024-10-01 14:13 UTC, robotmaxtron commented
/lgtm

2024-10-02 15:00 UTC, merged