Allow dediated-admin to manage project request templates
openshift/managed-cluster-config pull request #524
Opened 2020-10-21 19:10 UTC by fahlmant

From the ticket, this PR does the following:

-Remove SSS that creates / manages template "osd-project-request"
-Remove SSS that patches projects.config.openshift.io "cluster" resource
-Add RBAC to allow dedicated-admins to manage project.config.openshift.io

2020-10-21 19:11 UTC, lisa commented
/assign @jewzaam

2020-10-21 19:27 UTC, fahlmant commented
https://issues.redhat.com/browse/OSD-5566

2020-10-21 19:28 UTC, jewzaam requested changes

2020-10-21 19:28 UTC, jewzaam commented on deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
> +  - "project"
```suggestion
  - projects
```

2020-10-21 19:44 UTC, fahlmant commented
/hold

2020-10-21 20:50 UTC, jewzaam requested changes

2020-10-21 20:50 UTC, jewzaam commented on deploy/osd-project-request-template/04-patch.label-default-namespace.yaml
> -  { "metadata": {"labels": {"name":"default"} } }
Can't take this out without knowing who is using it.  Probably added to support NetworkPolicy for an internal customer.

2020-10-21 20:50 UTC, jewzaam commented on deploy/osd-project-request-template/02-role.dedicated-admins-project-request.yaml
> -  name: dedicated-admins-project-request
Can't take this out, it removes management of the template, which we're trying to allow.

2020-10-21 20:50 UTC, jewzaam commented on deploy/osd-project-request-template/03-rolebinding.dedicated-admins-project-request.yaml
> -  name: dedicated-admins-project-request
Need this to realize management of the template for the customer.

2020-10-21 20:50 UTC, jewzaam commented on deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml
> +  - "*"
```suggestion
  - get
  - list
  - patch
  - update
  - watch
```
Probably better to not allow delete, and therefore not allow create.

2020-10-22 16:03 UTC, fahlmant commented
Closing in favor of #528

2020-10-22 16:03 UTC, closed without merging