Add ClusterRole{Binding} for CustomDomain CR
openshift/managed-cluster-config pull request #552
Opened 2020-11-10 23:04 UTC by dustman9000

This permits dedicated-admins to create/update/delete/etc. the CustomDomain CR.

2020-11-11 15:30 UTC, jharrington22 approved these changes
/lgtm

2020-11-11 15:30 UTC, jharrington22 commented
/hold

2020-11-11 15:31 UTC, jharrington22 commented
@jewzaam can I get you to take a quick look

2020-11-13 21:08 UTC, jewzaam requested changes

2020-11-13 21:08 UTC, jewzaam commented on deploy/osd-custom-domains/01-dedicated-admins-cluster.ClusterRole.yaml
> +  name: osd-custom-domains-dedicated-admin-cluster
```suggestion
  labels:
    managed.openshift.io/aggregate-to-dedicated-admins: "cluster"
  name: osd-custom-domains-dedicated-admin-cluster
```

And remove the ClusterRoleBinding.  The label will aggregate to the `dedicated-admins-cluster` ClusterRole and it'll Just Work.

2020-11-18 20:21 UTC, jewzaam commented
/lgtm
/hold cancel

2020-11-18 20:37 UTC, merged