OHSS-2561 Extend hive integration token timeout
openshift/managed-cluster-config pull request #639
Opened 2021-01-27 05:59 UTC by mrbarge

This PR extends the authentication token timeout for Hive integration clusters to a week.

The change has been successfully tested (in `SyncSet` form) on a test cluster to verify correct syntax of the patch.

Refs: OHSS-2561 where this has been discussed.

2021-01-27 06:01 UTC, mrbarge commented
Want some :eyes: on this to make sure I've done it right, so just putting a hold on until then.
/hold

2021-01-27 13:07 UTC, jewzaam requested changes

2021-01-27 13:07 UTC, jewzaam commented on deploy/osd-oauth-templates/ohss-2561/config.yaml
> +  environments: ["integration"]
This is an interesting case I didn't consider when setting up Direct.  The yaml for the "patch" doesn't apply if you use `oc apply -f` but you can apply the patch via the hive managing integration:

```suggestion
deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: environment
    operator: In
    values: ["integration"]
  - key: ext-managed.openshift.io/hive-shard
    operator: In
    values: ["true"]
```

2021-01-27 13:07 UTC, jewzaam commented
/approve

Once this is sorted out, I'm good with the change.

2021-01-27 22:42 UTC, mrbarge commented
/hold cancel

2021-01-28 13:24 UTC, jewzaam commented
/lgtm

2021-01-28 13:31 UTC, merged