Install file-integrity-operator into staging
openshift/managed-cluster-config pull request #770
Opened 2021-03-24 19:16 UTC by clcollins

This commit adds the OpenShift file-integrity-operator to staging
clusters. Additionally adding:

  * Prometheus role and rolebindings for clustermonitoring
  * FileIntegrity object, to scan all nodes every 15 minutes for changes

This is preliminary to a full alerting deployment, so there are no
alerts or related notifications if a file integrity scan fails yet.

Signed-off-by: Chris Collins <collins.christopher@gmail.com>

2021-03-24 22:58 UTC, karthikperu7 requested changes

2021-03-24 22:58 UTC, karthikperu7 commented on deploy/osd-file-integrity-operator/config.yml
> +    api.openshift.com/legal-entity-id: "${{SREP_LEGAL_ENTITY_ID}}"
small nitpick about no newline in EOL

2021-03-25 00:04 UTC, karthikperu7 commented
/lgtm

2021-03-26 20:22 UTC, cblecker reviewed
@karthikperu7 I think you were looking into if we should provide some sort of catalog mirroring, yes? Was it for this operator?

2021-03-26 20:22 UTC, cblecker commented on deploy/osd-file-integrity-operator/20-fileIntegrityOperator-Subscription.yml
> +  channel: "4.6"
This channel works for the entire fleet? (4.5 through 4.7)

2021-03-26 20:22 UTC, cblecker commented on deploy/osd-file-integrity-operator/20-fileIntegrityOperator-Subscription.yml
> +  installPlanApproval: "Automatic"
Do we care if a bad version of this operator is pushed?

2021-08-24 08:45 UTC, closed without merging